## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------

admin = ENC(1024:F860A97BF4AE23F17616EDAA091E766887FAC1AB56F08A3690C8D321F55ACCA4:8644E0B6B14E5C823C1DA71E1F3FCD8E2DF6D1C0A97F4A526BC6DDD2402A650ECB7CDC27D798E060C6D94A650D0A0ECE8D2E10F5E3A743D15B8AD5C97BDE1C2D)